# Configure LGTM for this package

extraction:
  python:  # Configure Python
    python_setup:  # Configure the setup
      version: 3  # Specify Version 3
  cpp:
    prepare:
      packages:
        - python3-numpy

path_classifiers:
  test:
    - scripts/*
  library:
    - versioneer.py  # Set Versioneer.py to an external "library" (3rd party code)
  generated:
    - gau2grid/_version.py
