# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python
sudo: false
matrix:

  include:

  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.6
        packages:
        - clang-3.6
    env:
      - C_COMPILER='clang-3.6'
      - PYTHON_VER='3.7'
      - BUILD_TYPE='release'
      - SPHERICAL_ORDER='cca'

  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-5.0
        packages:
        - clang-5.0
    env:
      - C_COMPILER='clang-5.0'
      - PYTHON_VER='3.6'
      - BUILD_TYPE='release'
      - SPHERICAL_ORDER='gaussian'

  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.9
    env:
      - C_COMPILER='gcc-4.9'
      - PYTHON_VER='3.7'
      - BUILD_TYPE='release'
      - SPHERICAL_ORDER='cca'

  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-6
    env:
      - C_COMPILER='gcc-6'
      - PYTHON_VER='3.5'
      - BUILD_TYPE='release'
      - SPHERICAL_ORDER='cca'

  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
    env:
      - C_COMPILER='gcc-7'
      - PYTHON_VER='3.6'
      - BUILD_TYPE='release'
      - SPHERICAL_ORDER='gaussian'

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
    # Pull down a miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

    # Build out the environment
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n gg_env python=$PYTHON_VER numpy nomkl pytest cmake -c conda-forge
  - source activate gg_env

    # Install anything not in conda
  - pip install codecov pytest-cov
  - conda list
  - export

before_script:
  - python -V
  - python -c 'import numpy; print(numpy.version.version)'
  - >
    python setup.py install
    -DCMAKE_C_COMPILER=${C_COMPILER}
    -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
    -DSPHERICAL_ORDER=${SPHERICAL_ORDER}

script:
  - export GAU2GRID_FORCE_C_TEST=1
  - export SPDIR=`python -c 'from distutils import sysconfig as s; print(s.get_python_lib(plat_specific=True))'`
  - pytest -rws -v --durations=5 --cov=${SPDIR}/gau2grid/ --pyargs gau2grid

notifications:
  email: false

after_success:
  - codecov
