# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python
sudo: false
matrix:

  include:

  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.6
        packages:
        - clang-3.6
    env:
      - C_COMPILER='clang-3.6'
      - PYTHON_VER='2.7'
      - BUILD_TYPE='release'
      - DO_MPMATH=1
  
  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-5.0
        packages:
        - clang-5.0
    env:
      - C_COMPILER='clang-5.0'
      - PYTHON_VER='3.6'
      - BUILD_TYPE='release'
      - DO_MPMATH=0
  
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.9
    env:
      - C_COMPILER='gcc-4.9'
      - PYTHON_VER='2.7'
      - BUILD_TYPE='release'
      - DO_MPMATH=0

  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-6
    env:
      - C_COMPILER='gcc-6'
      - PYTHON_VER='3.5'
      - BUILD_TYPE='release'
      - DO_MPMATH=0

  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
    env:
      - C_COMPILER='gcc-7'
      - PYTHON_VER='3.6'
      - BUILD_TYPE='release'
      - DO_MPMATH=1

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
    # Pull down a miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

    # Build out the environment
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n gg_env python=$PYTHON_VER numpy nomkl pytest numexpr cmake -c conda-forge
  - source activate gg_env

    # Optionally install mpmath 
  - if [[ "$DO_MPMATH" == "1" ]]; then
        conda install mpmath;
    fi

    # Install anything not in conda
  - pip install codecov
  - pip install pytest-cov
  - conda list
  - export

before_script:
  - python -V
  - python -c 'import numpy; print(numpy.version.version)'
  - > 
    python setup.py develop
    -DCMAKE_C_COMPILER=${C_COMPILER}
    -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
    -DCMAKE_PREFIX_PATH=${CONDA_PREFIX}

script:
  - py.test -v --cov=gau2grid/ --durations=5

notifications:
  email: false

after_success:
  - codecov

